name: 'Run on Rhino Linux'
description: 'Custom Action to run commands in Rhino Linux'
author: 'Sundaram Krishnan'
branding:
  icon: 'terminal'
  color: 'blue'

inputs:
  arch:
    description: 'CPU Architecture: amd64, arm64, x86_64, aarch64'
    required: true
  
  run: 
    description: 'Shell commands to execute in Rhino Linux'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.arch }}
    - ${{ inputs.run }}