name: 'Run on Rhino Linux'
description: 'Custom Action to run commands in Rhino Linux'
author: 'Sundaram Krishnan'
branding:
  icon: 'terminal'
  color: 'blue'

inputs:
  message:
    description: 'Test'
    required: true
    default: 'Hello World'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.message }}
